### ISSUE TITLE
Installation failure on Firefox 59

### ISSUE THREAD

**Issue by antrik** [blaise-io/forget-about-this-site#2]
I get a `Download failed. Please check your connection.` message displayed on the extension page. ( https://addons.mozilla.org/en-US/firefox/addon/forget-about-this-site/ ) Other extensions install just fine on the same instance.

This is with Firefox 59.0.2 (32-bit) on GNU/Linux. (No problem with 65.0.1 -- the latter is a binary from Mozilla though, while the former is an outdated Debian package...)

**Comment by blaise-io** [comment]
I'm not going to fix this any more :)
