### ISSUE TITLE
can a confirmation be added  BEFORE deletion?

### ISSUE THREAD

**Issue by rezad1393** [blaise-io/forget-about-this-site#9]
the user can accidentally click on the icon instead of bookmark icon.

**Comment by blaise-io** [comment]
I guess this is Firefox? Maybe you can unpin it from the address bar, which would move it to the ••• menu.

**Comment by rezad1393** [comment]
> I guess this is Firefox? Maybe you can unpin it from the address bar, which would move it to the ••• menu.

already did that but still a confirmation would be nice.

**Comment by blaise-io** [comment]
I'm working on this in https://github.com/blaise-io/forget-about-this-site/tree/9-ask-confirmation, reminder to self: test in Chrome and translate new strings.

**Comment by rezad1393** [comment]
> I guess this is Firefox? Maybe you can unpin it from the address bar, which would move it to the ••• menu.

as you can see with newest firefox update that option was destroyed.

**Comment by blaise-io** [comment]
But the confirmation is implemented now :)
